--require("brian.plugins.catppuccin")
require("brian.plugins.mini")
require("brian.plugins.whichkey")
require("brian.plugins.nvim-tree")
require("brian.plugins.treesitter")
require("brian.plugins.lspconfig")
require("brian.plugins.null-ls")
require("brian.plugins.toggleterm")
